#!/bin/bash
set -e

# Default values
PROJECT_NAME=""
ENV_NAME=""
MOUNT_PATH=".env"
SETUP_CURSOR_HOOKS=true
PROJECT_ROOT=""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --project-name)
      PROJECT_NAME="$2"
      shift 2
      ;;
    --env-name)
      ENV_NAME="$2"
      shift 2
      ;;
    --mount-path)
      MOUNT_PATH="$2"
      shift 2
      ;;
    --no-cursor-hooks)
      SETUP_CURSOR_HOOKS=false
      shift
      ;;
    --project-root)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    -h|--help)
      cat << EOF
Usage: $0 [OPTIONS]

Create a 1Password Environment setup for a project.

OPTIONS:
  --project-name NAME    Name of the project (required)
  --env-name NAME        Name for 1Password Environment (default: project-name)
  --mount-path PATH      Path for .env file (default: .env in project root)
  --project-root PATH    Project root directory (default: current directory)
  --no-cursor-hooks      Skip Cursor hooks setup
  -h, --help             Show this help message

EXAMPLES:
  $0 --project-name myapp
  $0 --project-name myapp --env-name myapp-dev --mount-path .env.local
  $0 --project-name myapp --project-root /path/to/project
EOF
      exit 0
      ;;
    *)
      echo -e "${RED}Error: Unknown option $1${NC}" >&2
      exit 1
      ;;
  esac
done

# Determine project root
if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT=$(pwd)
fi

# Validate project root exists
if [ ! -d "$PROJECT_ROOT" ]; then
  echo -e "${RED}Error: Project root directory does not exist: $PROJECT_ROOT${NC}" >&2
  exit 1
fi

# Auto-detect project name from git if not provided
if [ -z "$PROJECT_NAME" ]; then
  if [ -d "$PROJECT_ROOT/.git" ]; then
    PROJECT_NAME=$(basename "$(git -C "$PROJECT_ROOT" rev-parse --show-toplevel 2>/dev/null || echo "$PROJECT_ROOT")")
    echo -e "${YELLOW}Auto-detected project name: $PROJECT_NAME${NC}"
  else
    PROJECT_NAME=$(basename "$PROJECT_ROOT")
    echo -e "${YELLOW}Using directory name as project name: $PROJECT_NAME${NC}"
  fi
fi

# Set default env name if not provided
if [ -z "$ENV_NAME" ]; then
  ENV_NAME="$PROJECT_NAME"
fi

# Normalize mount path (make absolute if relative)
if [[ "$MOUNT_PATH" != /* ]]; then
  MOUNT_PATH="$PROJECT_ROOT/$MOUNT_PATH"
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}1Password Environment Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "Project Name: ${GREEN}$PROJECT_NAME${NC}"
echo -e "Environment Name: ${GREEN}$ENV_NAME${NC}"
echo -e "Mount Path: ${GREEN}$MOUNT_PATH${NC}"
echo -e "Project Root: ${GREEN}$PROJECT_ROOT${NC}"
echo -e "Setup Cursor Hooks: ${GREEN}$SETUP_CURSOR_HOOKS${NC}"
echo ""

# Create .1password directory
mkdir -p "$PROJECT_ROOT/.1password"

# Create environments.toml
ENV_TOML="$PROJECT_ROOT/.1password/environments.toml"
cat > "$ENV_TOML" << EOF
# 1Password Environment Configuration
# Generated by create_project_environment.sh

# List of .env file paths to validate
# Paths can be relative to project root or absolute
mount_paths = ["$MOUNT_PATH"]
EOF

echo -e "${GREEN}✓${NC} Created $ENV_TOML"

# Setup Cursor hooks if requested
if [ "$SETUP_CURSOR_HOOKS" = true ]; then
  echo ""
  echo -e "${BLUE}Setting up Cursor hooks...${NC}"
  
  # Create .cursor/hooks directory
  mkdir -p "$PROJECT_ROOT/.cursor/hooks"
  
  # Copy or symlink 1password hook
  if [ -d ~/.cursor/hooks/1password ]; then
    if [ ! -e "$PROJECT_ROOT/.cursor/hooks/1password" ]; then
      # Try to create symlink first (preferred)
      if ln -s ~/.cursor/hooks/1password "$PROJECT_ROOT/.cursor/hooks/1password" 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Created symlink to 1password hook"
      else
        # Fallback to copy
        cp -r ~/.cursor/hooks/1password "$PROJECT_ROOT/.cursor/hooks/"
        echo -e "${GREEN}✓${NC} Copied 1password hook to project"
      fi
    else
      echo -e "${YELLOW}⚠${NC} 1password hook already exists in project"
    fi
  else
    echo -e "${YELLOW}⚠${NC} User-level 1password hook not found at ~/.cursor/hooks/1password"
    echo -e "${YELLOW}   ${NC} Skipping hook setup. Install hooks first (see CURSOR_HOOKS_SETUP.md)"
  fi
  
  # Create or update .cursor/hooks.json
  HOOKS_JSON="$PROJECT_ROOT/.cursor/hooks.json"
  if [ -f "$HOOKS_JSON" ]; then
    echo -e "${YELLOW}⚠${NC} $HOOKS_JSON already exists. Please add the hook manually:"
    echo ""
    cat << 'EOF'
{
  "version": 1,
  "hooks": {
    "beforeShellExecution": [
      {
        "command": ".cursor/hooks/1password/validate-mounted-env-files.sh"
      }
    ]
  }
}
EOF
    echo ""
  else
    cat > "$HOOKS_JSON" << 'EOF'
{
  "version": 1,
  "hooks": {
    "beforeShellExecution": [
      {
        "command": ".cursor/hooks/1password/validate-mounted-env-files.sh"
      }
    ]
  }
}
EOF
    echo -e "${GREEN}✓${NC} Created $HOOKS_JSON"
  fi
fi

# Generate instructions file
INSTRUCTIONS_FILE="$PROJECT_ROOT/.1password/SETUP_INSTRUCTIONS.md"
cat > "$INSTRUCTIONS_FILE" << EOF
# 1Password Environment Setup Instructions

## Environment: $ENV_NAME

### Step 1: Create Environment in 1Password

1. Open **1Password Desktop App**
2. Go to **Developer > Environments**
3. Click **+** or **New Environment**
4. Name it: **$ENV_NAME**

### Step 2: Configure Local .env File

1. In the environment settings, find **Local .env file** or **Destination**
2. Set the path to: **$MOUNT_PATH**
3. Save the configuration

### Step 3: Import Credentials (Optional)

If you have a .env file to import:

1. In the environment view, click **Import** or **Import .env file**
2. Select your .env file
3. Review and confirm the import

### Step 4: Enable the Environment

1. Toggle the environment to **Enabled**
2. 1Password will create the FIFO file at: **$MOUNT_PATH**

### Step 5: Verify Setup

1. Check that the file exists: \`ls -l $MOUNT_PATH\`
2. It should be a FIFO (named pipe), not a regular file
3. Test in Cursor - the hook should validate the file automatically

## Troubleshooting

- **File not found:** Ensure the environment is enabled in 1Password
- **Not a FIFO:** The file must be created by 1Password, not manually
- **Hook not working:** Check Cursor's execution log (Settings > Hooks > Execution Log)

## Next Steps

- See \`../config/api-credentials/CURSOR_HOOKS_SETUP.md\` for hook configuration details
- See \`../config/api-credentials/SETUP_GUIDE.md\` for complete setup guide
EOF

echo -e "${GREEN}✓${NC} Created setup instructions: $INSTRUCTIONS_FILE"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "Next steps:"
echo -e "1. ${YELLOW}Open 1Password Desktop App${NC}"
echo -e "2. ${YELLOW}Create environment: $ENV_NAME${NC}"
echo -e "3. ${YELLOW}Configure local .env file path: $MOUNT_PATH${NC}"
echo -e "4. ${YELLOW}Enable the environment${NC}"
echo ""
echo -e "See detailed instructions in: ${BLUE}$INSTRUCTIONS_FILE${NC}"
echo ""

